"""Added container column and relationship in GJTest model

Revision ID: 04f65be4318d
Revises: a46636c59d26
Create Date: 2023-01-26 13:16:37.074803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f65be4318d'
down_revision = 'a46636c59d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_test_specimen_containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specimen_container', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gj_test_specimen_containers', ['container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('container_id')

    op.drop_table('gj_test_specimen_containers')
    # ### end Alembic commands ###
