"""Changed type from string to text in interference_analysis column

Revision ID: 111e334f07ad
Revises: 6e4ffc7cb4b1
Create Date: 2023-01-23 12:15:14.998503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111e334f07ad'
down_revision = '6e4ffc7cb4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_waiting_periods', schema=None) as batch_op:
        batch_op.drop_column('waiting_time')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('interference_analysis',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('specimen_quantity')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('interference_analysis',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('gj_test_waiting_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_time', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
