"""renamed permission to is_admin column in User model

Revision ID: 1128122c19ad
Revises: 6fa84e1adfe2
Create Date: 2023-03-01 15:52:06.008527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128122c19ad'
down_revision = '6fa84e1adfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('permission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
