"""Removed specimen container both column and relationship in GJTest model

Revision ID: 1b657de0396c
Revises: 04f65be4318d
Create Date: 2023-01-26 15:33:46.254282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b657de0396c'
down_revision = '04f65be4318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint('gj_tests_container_id_fkey', type_='foreignkey')
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gj_tests_container_id_fkey', 'gj_test_specimen_containers', ['container_id'], ['id'])

    # ### end Alembic commands ###
