"""Dropped specimen date time and location column in GJTestSpecimen model

Revision ID: 20db264f6a49
Revises: 48a0b8fb0ee5
Create Date: 2022-12-29 15:33:41.373657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20db264f6a49'
down_revision = '48a0b8fb0ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_test_specimen_transportations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specimen_date_time', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['gj_test_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.drop_constraint('gj_test_specimens_location_id_fkey', type_='foreignkey')
        batch_op.drop_column('specimen_date_time')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_date_time', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gj_test_specimens_location_id_fkey', 'gj_test_locations', ['location_id'], ['id'])

    op.drop_table('gj_test_specimen_transportations')
    # ### end Alembic commands ###
