"""Added specimen transportation id column and relationship in GJTest model

Revision ID: 2116032ecc42
Revises: 20db264f6a49
Create Date: 2022-12-29 15:47:40.380739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2116032ecc42'
down_revision = '20db264f6a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_transportation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gj_test_specimen_transportations', ['specimen_transportation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specimen_transportation_id')

    # ### end Alembic commands ###
