"""added updated at field

Revision ID: 254365d7558b
Revises: aaeb291576e1
Create Date: 2023-08-19 09:36:41.375521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254365d7558b'
down_revision = 'aaeb291576e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
