"""added updated by field

Revision ID: 36e86c2fc969
Revises: 254365d7558b
Create Date: 2023-08-21 22:18:50.027713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e86c2fc969'
down_revision = '254365d7558b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
