"""Added __versioned__ to all models you wish to add versioning to

Revision ID: 3dbf1b9cb7d6
Revises: 677a69b67a90
Create Date: 2023-04-25 14:59:51.015458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbf1b9cb7d6'
down_revision = '677a69b67a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_test_specimen_source_assoc_version',
    sa.Column('test_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('test_id', 'source_id', 'transaction_id')
    )
    with op.batch_alter_table('db_test_specimen_source_assoc_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_db_test_specimen_source_assoc_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_db_test_specimen_source_assoc_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_db_test_specimen_source_assoc_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('gj_tests_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('test_name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('prepare', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('solution', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('test_date_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('time_period_request_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('waiting_period_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reporting_referral_values', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('interference_analysis', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('caution', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('drop_off_location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('specimen_transportation_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gj_tests_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gj_tests_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gj_tests_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gj_tests_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_gj_tests_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_gj_tests_version_end_transaction_id'))

    op.drop_table('gj_tests_version')
    with op.batch_alter_table('db_test_specimen_source_assoc_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_db_test_specimen_source_assoc_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_db_test_specimen_source_assoc_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_db_test_specimen_source_assoc_version_end_transaction_id'))

    op.drop_table('db_test_specimen_source_assoc_version')
    # ### end Alembic commands ###
