"""Added many to many relationship in GJTest model

Revision ID: 4197a66b6bc7
Revises: 1b657de0396c
Create Date: 2023-01-26 15:59:10.252137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4197a66b6bc7'
down_revision = '1b657de0396c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_test_specimen_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specimen_type', sa.String(), nullable=True),
    sa.Column('specimen_quantity', sa.String(), nullable=True),
    sa.Column('specimen_container', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_test_specimen_source_assoc',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['gj_test_specimen_sources.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['gj_tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_test_specimen_source_assoc')
    op.drop_table('gj_test_specimen_sources')
    # ### end Alembic commands ###
