"""Removed type of string column

Revision ID: 435b362b9197
Revises: 5f4db5559dd2
Create Date: 2023-01-26 17:48:01.661604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435b362b9197'
down_revision = '5f4db5559dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimen_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimens_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specimen_quantity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specimen_container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gj_test_specimen_containers', ['specimen_container_id'], ['id'])
        batch_op.create_foreign_key(None, 'gj_test_specimens', ['specimens_id'], ['id'])
        batch_op.create_foreign_key(None, 'gj_test_specimen_quantities', ['specimen_quantity_id'], ['id'])
        batch_op.drop_column('specimen_container')
        batch_op.drop_column('specimen_type')
        batch_op.drop_column('specimen_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimen_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_container', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specimen_container_id')
        batch_op.drop_column('specimen_quantity_id')
        batch_op.drop_column('specimens_id')

    # ### end Alembic commands ###
