"""Dropped time_period_request column in GJTest model

Revision ID: 48a0b8fb0ee5
Revises: e5c825b61ee4
Create Date: 2022-12-29 14:57:22.075496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a0b8fb0ee5'
down_revision = 'e5c825b61ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('time_period_requested')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_period_requested', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
