"""Added unit column and to dict in GJTestSpecimenQuantity model

Revision ID: 48f9a829be70
Revises: f60913da0bd8
Create Date: 2023-01-23 13:23:50.739296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f9a829be70'
down_revision = 'f60913da0bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimen_quantities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimen_quantities', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
