"""deleted unused fields

Revision ID: 585dc5adf1fa
Revises: d39d1ee527c6
Create Date: 2023-01-30 03:52:33.249921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585dc5adf1fa'
down_revision = 'd39d1ee527c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint('gj_tests_specimen_container_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('gj_tests_quantity_id_fkey', type_='foreignkey')
        batch_op.drop_column('quantity_id')
        batch_op.drop_column('specimen_container_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_container_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gj_tests_quantity_id_fkey', 'gj_test_specimen_quantities', ['quantity_id'], ['id'])
        batch_op.create_foreign_key('gj_tests_specimen_container_id_fkey', 'gj_test_specimen_containers', ['specimen_container_id'], ['id'])

    # ### end Alembic commands ###
