"""Added specimen_container column and relationship in GJTest model

Revision ID: 5f4db5559dd2
Revises: 4197a66b6bc7
Create Date: 2023-01-26 16:12:03.277084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4db5559dd2'
down_revision = '4197a66b6bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gj_test_specimen_containers', ['specimen_container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specimen_container_id')

    # ### end Alembic commands ###
