"""Removed GJTestLog model

Revision ID: 677a69b67a90
Revises: 0eea3a551175
Create Date: 2023-03-08 13:20:32.139413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a69b67a90'
down_revision = '0eea3a551175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gj_test_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_test_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['gj_tests.id'], name='gj_test_logs_test_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gj_test_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gj_test_logs_pkey')
    )
    # ### end Alembic commands ###
