"""Edited type of solution column from string to text in GJTest model

Revision ID: 7800511fe39b
Revises: 585dc5adf1fa
Create Date: 2023-01-31 09:49:41.082833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7800511fe39b'
down_revision = '585dc5adf1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('solution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('gj_tests_specimen_container_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('gj_tests_quantity_id_fkey', type_='foreignkey')
        batch_op.drop_column('specimen_container_id')
        batch_op.drop_column('quantity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_container_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gj_tests_quantity_id_fkey', 'gj_test_specimen_quantities', ['quantity_id'], ['id'])
        batch_op.create_foreign_key('gj_tests_specimen_container_id_fkey', 'gj_test_specimen_containers', ['specimen_container_id'], ['id'])
        batch_op.alter_column('solution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
