"""added price related fields

Revision ID: 8115adcf6ce0
Revises: ca528fc72bc5
Create Date: 2025-02-21 11:18:56.495536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8115adcf6ce0'
down_revision = 'ca528fc72bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_reimbursable_price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('reimbursable_price', sa.Numeric(), nullable=True))

    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_reimbursable_price', sa.Numeric(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reimbursable_price', sa.Numeric(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.drop_column('reimbursable_price')
        batch_op.drop_column('non_reimbursable_price')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('reimbursable_price')
        batch_op.drop_column('non_reimbursable_price')

    # ### end Alembic commands ###
