"""Changed type of caution from string to text in GJTest model

Revision ID: 866ba8a6a606
Revises: e97a7914cf7b
Create Date: 2023-02-03 15:36:09.099442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866ba8a6a606'
down_revision = 'e97a7914cf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('caution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('caution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
