"""removed specimen_container in GJTestSpecimen

Revision ID: a46636c59d26
Revises: 48f9a829be70
Create Date: 2023-01-26 13:07:22.594228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46636c59d26'
down_revision = '48f9a829be70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.drop_column('specimen_container')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_container', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
