"""added tables for versioning

Revision ID: aaeb291576e1
Revises: 3dbf1b9cb7d6
Create Date: 2023-08-07 14:29:06.927900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaeb291576e1'
down_revision = '3dbf1b9cb7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###
