""" Added specimen_container column in GJTestSpecimen model

Revision ID: b1bea04a8d07
Revises: f32eec694fee
Create Date: 2023-01-18 14:49:58.258862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bea04a8d07'
down_revision = 'f32eec694fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_container', sa.String(), nullable=True))


    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('specimen_container')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_container', sa.VARCHAR(), autoincrement=False, nullable=True))


    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.drop_column('specimen_container')

    # ### end Alembic commands ###
