"""Added specimens for many to many in GJTest model

Revision ID: b80210206543
Revises: 02d1942af1ed
Create Date: 2023-01-20 15:33:33.757337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80210206543'
down_revision = '02d1942af1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_test_specimen_assoc_assoc',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('specimen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specimen_id'], ['gj_test_specimens.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['gj_tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'specimen_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_test_specimen_assoc_assoc')
    # ### end Alembic commands ###
