"""Added request from url column in GJTest model

Revision ID: c60f3c12a99f
Revises: f974d5959e22
Create Date: 2023-08-16 11:02:56.822570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60f3c12a99f'
down_revision = 'f974d5959e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_form_url', sa.Text(), nullable=True))
        batch_op.alter_column('outsource_lab_test_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_form_url', sa.Text(), autoincrement=False, nullable=True))
        batch_op.alter_column('outsource_lab_test_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.alter_column('outsource_lab_test_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               autoincrement=False)
        batch_op.drop_column('request_form_url')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('outsource_lab_test_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('request_form_url')

    # ### end Alembic commands ###
