"""removed unique constraint from code field

Revision ID: ca528fc72bc5
Revises: 7a2e98e656b4
Create Date: 2023-10-04 16:19:28.795474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca528fc72bc5'
down_revision = '7a2e98e656b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint('gj_tests_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.create_unique_constraint('gj_tests_code_key', ['code'])

    # ### end Alembic commands ###
