"""set test name and code non-nullable

Revision ID: d39d1ee527c6
Revises: 435b362b9197
Create Date: 2023-01-30 03:11:13.015527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39d1ee527c6'
down_revision = '435b362b9197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('test_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
