"""Added specimen_quantity, specimen_container, and unit in GJTest model

Revision ID: f32eec694fee
Revises: c7be9a503fbd
Create Date: 2023-01-10 10:57:17.363926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32eec694fee'
down_revision = 'c7be9a503fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.drop_column('specimen_container')
        batch_op.drop_column('unit')
        batch_op.drop_column('specimen_quantity')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_quantity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('specimen_container', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('specimen_container')
        batch_op.drop_column('specimen_quantity')

    with op.batch_alter_table('gj_test_specimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specimen_container', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
