"""Added GJTestSpecimenQuantity model

Revision ID: f60913da0bd8
Revises: 111e334f07ad
Create Date: 2023-01-23 12:54:15.763181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60913da0bd8'
down_revision = '111e334f07ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gj_test_specimen_quantities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specimen_quantity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gj_test_specimen_quantities', ['quantity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity_id')

    op.drop_table('gj_test_specimen_quantities')
    # ### end Alembic commands ###
