"""Added outsource_lab_test_url column in GJTest model

Revision ID: f974d5959e22
Revises: aaeb291576e1
Create Date: 2023-08-15 16:29:41.179748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f974d5959e22'
down_revision = 'aaeb291576e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outsource_lab_test_url', sa.String(), nullable=True))

    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outsource_lab_test_url', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gj_tests_version', schema=None) as batch_op:
        batch_op.drop_column('outsource_lab_test_url')

    with op.batch_alter_table('gj_tests', schema=None) as batch_op:
        batch_op.drop_column('outsource_lab_test_url')

    # ### end Alembic commands ###
